const BASE_URL = process.env.NEXT_PUBLIC_API_LINK;

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: `${BASE_URL}/api/v1/authentication/register`,
    LOGIN: `${BASE_URL}/api/v1/authorization/login`,
  },
  DASHBOARD: {
    LOCATIONS: {
      BULK_UPLOAD_LOCATIONS: `${BASE_URL}/api/v1/location/bulk-upload`,
      GET_LOCATIONS: `${BASE_URL}/api/v1/location/all`,
    },
    USERS: {
      GET_USERS: `${BASE_URL}/api/v1/user/all`,
      GET_USERS_STATS: `${BASE_URL}/api/v1/user/stats`,
      GET_TOTAL_USERS: `${BASE_URL}/api/v1/user/all`,
      DELETE_USER: `${BASE_URL}/api/v1/user/delete`,
      UNDELETE_USER: `${BASE_URL}/api/v1/user/un-delete`,
      SWITCH_USER_ACTIVE_STATUS: `${BASE_URL}/api/v1/user/status`,
      GET_ACTIVE_USERS: `${BASE_URL}/api/v1/user/all`,
      GET_DELETED_USERS: `${BASE_URL}/api/v1/user/all`,
      GET_ADMIN_USERS: `${BASE_URL}/api/v1/user/all`,
      CREATE_ADMIN: `${BASE_URL}/api/v1/user/create-admin`,
      UPDATE_ADMIN: `${BASE_URL}/api/v1/user/update-admin`,
    },
    CATEGORIES: {
      ACTIVE: `${BASE_URL}/api/v1/category/active`,
      GET_ALL: `${BASE_URL}/api/v1/category/all`,
      DELETE: `${BASE_URL}/api/v1/category/delete`,
      UN_DELETE: `${BASE_URL}/api/v1/category/un-delete`,
      SWITCH_ACTIVE_STATUS: `${BASE_URL}/api/v1/category/status`,
      CREATE: `${BASE_URL}/api/v1/category/create`,
      EDIT: `${BASE_URL}/api/v1/category/update`,
    },
    SUB_CATEGORIES: {
      GET_ALL: `${BASE_URL}/api/v1/sub-category/all`,
      DELETE: `${BASE_URL}/api/v1/sub-category/delete`,
      UN_DELETE: `${BASE_URL}/api/v1/sub-category/un-delete`,
      SWITCH_ACTIVE_STATUS: `${BASE_URL}/api/v1/sub-category/status`,
      CREATE: `${BASE_URL}/api/v1/sub-category/create`,
      EDIT: `${BASE_URL}/api/v1/sub-category/update`,
    },
    PRODUCTS: {
      ALL: `${BASE_URL}/api/v1/product/all`,
      DELETE: `${BASE_URL}/api/v1/product/delete`,
      UN_DELETE: `${BASE_URL}/api/v1/product/un-delete`,
      SWITCH_ACTIVE_STATUS: `${BASE_URL}/api/v1/product/status`,
      CREATE: `${BASE_URL}/api/v1/product/create`,
      EDIT: `${BASE_URL}/api/v1/product/update`,
    },
    LOGOS: {
      ALL: `${BASE_URL}/api/v1/logo/all`,
      DELETE: `${BASE_URL}/api/v1/logo/delete`,
      UN_DELETE: `${BASE_URL}/api/v1/logo/un-delete`,
      SWITCH_ACTIVE_STATUS: `${BASE_URL}/api/v1/logo/status`,
      CREATE: `${BASE_URL}/api/v1/logo/create`,
      EDIT: `${BASE_URL}/api/v1/logo/update`,
      ACTIVE: `${BASE_URL}/api/v1/logo/active`,
    },
    BANNERS: {
      ALL: `${BASE_URL}/api/v1/banner/all`,
      DELETE: `${BASE_URL}/api/v1/banner/delete`,
      UN_DELETE: `${BASE_URL}/api/v1/banner/un-delete`,
      SWITCH_ACTIVE_STATUS: `${BASE_URL}/api/v1/banner/status`,
      CREATE: `${BASE_URL}/api/v1/banner/create`,
      EDIT: `${BASE_URL}/api/v1/banner/update`,
      ACTIVE: `${BASE_URL}/api/v1/banner/active`,
    },
    TYPE_HINT_CONFIGS: {
      ALL: `${BASE_URL}/api/v1/type-hint-config/all`,
      LIST: `${BASE_URL}/api/v1/type-hint-config/list`,
      DELETE: `${BASE_URL}/api/v1/type-hint-config/delete`,
      UN_DELETE: `${BASE_URL}/api/v1/type-hint-config/un-delete`,
      SWITCH_ACTIVE_STATUS: `${BASE_URL}/api/v1/type-hint-config/status`,
      CREATE: `${BASE_URL}/api/v1/type-hint-config/create`,
      EDIT: `${BASE_URL}/api/v1/type-hint-config/update`,
      ACTIVE: `${BASE_URL}/api/v1/type-hint-config/active`,
    },
    SHOWCASES: {
      ALL: `${BASE_URL}/api/v1/showcase/all`,
      DELETE: `${BASE_URL}/api/v1/showcase/delete`,
      UN_DELETE: `${BASE_URL}/api/v1/showcase/un-delete`,
      SWITCH_ACTIVE_STATUS: `${BASE_URL}/api/v1/showcase/status`,
      CREATE: `${BASE_URL}/api/v1/showcase/create`,
      EDIT: `${BASE_URL}/api/v1/showcase/update`,
      ACTIVE: `${BASE_URL}/api/v1/showcase/active`,
    },
    WISHLIST: {
      ONE: `${BASE_URL}/api/v1/wish-list`,
      ADD: `${BASE_URL}/api/v1/wish-list/add`,
      REMOVE: `${BASE_URL}/api/v1/wish-list/remove`,
      REMOVE_ALL: `${BASE_URL}/api/v1/wish-list/remove-all`,
    },
  },
  HOME: {
    PRODUCTS: {
      CATEGORIES_PICKS: `${BASE_URL}/api/v1/product/categories-picks`,
    },
  },
  LOGGED_USER: {
    WISHLIST: {
      ONE: `${BASE_URL}/api/v1/wish-list`,
      ADD: `${BASE_URL}/api/v1/wish-list/add`,
      REMOVE: `${BASE_URL}/api/v1/wish-list/remove`,
      REMOVE_ALL: `${BASE_URL}/api/v1/wish-list/remove-all`,
    },
  },
  CATEGORY: {
    ONE: `${BASE_URL}/api/v1/category`,
    PRODUCTS: `${BASE_URL}/api/v1/product/all`,
  },
  SUB_CATEGORY: {
    ONE: `${BASE_URL}/api/v1/sub-category`,
    PRODUCTS: `${BASE_URL}/api/v1/product/all`,
  },
  PRODUCT: {
    ONE: `${BASE_URL}/api/v1/product`,
    COMMENTS: `${BASE_URL}/api/v1/comment/all`,
    ADD_COMMENT: `${BASE_URL}/api/v1/comment/create`,
    EDIT_COMMENT: `${BASE_URL}/api/v1/comment/update`,
    DELETE_COMMENT: `${BASE_URL}/api/v1/comment/delete`,
    SUGGESTED: `${BASE_URL}/api/v1/product/suggested`,
  },
  SEARCH: {
    ROOT: `${BASE_URL}/api/v1/search`,
    PRODUCTS: `${BASE_URL}/api/v1/search/products`,
  },
};
