const API_URL = process.env.NEXT_PUBLIC_API_LINK;

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: `${API_URL}/api/v1/authentication/register`,
    LOGIN: `${API_URL}/api/v1/authorization/login`,
    FORGOT_PASSWORD: {
      ROOT: `${API_URL}/api/v1/authentication/forgot-password`,
      SEND_IDENTIFIER: "send-identifier",
      VERIFY_CODE: "verify-reset-password-code",
      RESET_PASSWORD: "reset-password",
    },
  },
  AUTHORIZATION: { LOGIN: `${API_URL}/api/v1/authorization/login` },
  DASHBOARD: {
    LOCATIONS: {
      BULK_UPLOAD_LOCATIONS: `${API_URL}/api/v1/location/bulk-upload`,
      GET_LOCATIONS: `${API_URL}/api/v1/location/all`,
    },
    USERS: {
      GET_USERS: `${API_URL}/api/v1/user/all`,
      GET_USERS_STATS: `${API_URL}/api/v1/user/stats`,
      GET_TOTAL_USERS: `${API_URL}/api/v1/user/all`,
      DELETE_USER: `${API_URL}/api/v1/user/delete`,
      UNDELETE_USER: `${API_URL}/api/v1/user/un-delete`,
      SWITCH_USER_ACTIVE_STATUS: `${API_URL}/api/v1/user/status`,
      GET_ACTIVE_USERS: `${API_URL}/api/v1/user/all`,
      GET_DELETED_USERS: `${API_URL}/api/v1/user/all`,
      GET_ADMIN_USERS: `${API_URL}/api/v1/user/all`,
      CREATE_ADMIN: `${API_URL}/api/v1/user/create-admin`,
      UPDATE_ADMIN: `${API_URL}/api/v1/user/update-admin`,
    },
    CATEGORIES: {
      ACTIVE: `${API_URL}/api/v1/category/active`,
      GET_ALL: `${API_URL}/api/v1/category/all`,
      DELETE: `${API_URL}/api/v1/category/delete`,
      UN_DELETE: `${API_URL}/api/v1/category/un-delete`,
      SWITCH_ACTIVE_STATUS: `${API_URL}/api/v1/category/status`,
      CREATE: `${API_URL}/api/v1/category/create`,
      EDIT: `${API_URL}/api/v1/category/update`,
    },
    SUB_CATEGORIES: {
      GET_ALL: `${API_URL}/api/v1/sub-category/all`,
      DELETE: `${API_URL}/api/v1/sub-category/delete`,
      UN_DELETE: `${API_URL}/api/v1/sub-category/un-delete`,
      SWITCH_ACTIVE_STATUS: `${API_URL}/api/v1/sub-category/status`,
      CREATE: `${API_URL}/api/v1/sub-category/create`,
      EDIT: `${API_URL}/api/v1/sub-category/update`,
    },
    PRODUCTS: {
      ALL: `${API_URL}/api/v1/product/all`,
      DELETE: `${API_URL}/api/v1/product/delete`,
      UN_DELETE: `${API_URL}/api/v1/product/un-delete`,
      SWITCH_ACTIVE_STATUS: `${API_URL}/api/v1/product/status`,
      CREATE: `${API_URL}/api/v1/product/create`,
      EDIT: `${API_URL}/api/v1/product/update`,
    },
    LOGOS: {
      ALL: `${API_URL}/api/v1/logo/all`,
      DELETE: `${API_URL}/api/v1/logo/delete`,
      UN_DELETE: `${API_URL}/api/v1/logo/un-delete`,
      SWITCH_ACTIVE_STATUS: `${API_URL}/api/v1/logo/status`,
      CREATE: `${API_URL}/api/v1/logo/create`,
      EDIT: `${API_URL}/api/v1/logo/update`,
      ACTIVE: `${API_URL}/api/v1/logo/active`,
    },
    BANNERS: {
      ALL: `${API_URL}/api/v1/banner/all`,
      DELETE: `${API_URL}/api/v1/banner/delete`,
      UN_DELETE: `${API_URL}/api/v1/banner/un-delete`,
      SWITCH_ACTIVE_STATUS: `${API_URL}/api/v1/banner/status`,
      CREATE: `${API_URL}/api/v1/banner/create`,
      EDIT: `${API_URL}/api/v1/banner/update`,
      ACTIVE: `${API_URL}/api/v1/banner/active`,
    },
    TYPE_HINT_CONFIGS: {
      ALL: `${API_URL}/api/v1/type-hint-config/all`,
      LIST: `${API_URL}/api/v1/type-hint-config/list`,
      DELETE: `${API_URL}/api/v1/type-hint-config/delete`,
      UN_DELETE: `${API_URL}/api/v1/type-hint-config/un-delete`,
      SWITCH_ACTIVE_STATUS: `${API_URL}/api/v1/type-hint-config/status`,
      CREATE: `${API_URL}/api/v1/type-hint-config/create`,
      EDIT: `${API_URL}/api/v1/type-hint-config/update`,
      ACTIVE: `${API_URL}/api/v1/type-hint-config/active`,
    },
    SHOWCASES: {
      ALL: `${API_URL}/api/v1/showcase/all`,
      DELETE: `${API_URL}/api/v1/showcase/delete`,
      UN_DELETE: `${API_URL}/api/v1/showcase/un-delete`,
      SWITCH_ACTIVE_STATUS: `${API_URL}/api/v1/showcase/status`,
      CREATE: `${API_URL}/api/v1/showcase/create`,
      EDIT: `${API_URL}/api/v1/showcase/update`,
      ACTIVE: `${API_URL}/api/v1/showcase/active`,
    },
    WISHLIST: {
      ONE: `${API_URL}/api/v1/wish-list`,
      ADD: `${API_URL}/api/v1/wish-list/add`,
      REMOVE: `${API_URL}/api/v1/wish-list/remove`,
      REMOVE_ALL: `${API_URL}/api/v1/wish-list/remove-all`,
    },
  },
  HOME: {
    PRODUCTS: {
      CATEGORIES_PICKS: `${API_URL}/api/v1/product/categories-picks`,
    },
  },
  LOGGED_USER: {
    WISHLIST: {
      ONE: `${API_URL}/api/v1/wish-list`,
      ADD: `${API_URL}/api/v1/wish-list/add`,
      REMOVE: `${API_URL}/api/v1/wish-list/remove`,
      REMOVE_ALL: `${API_URL}/api/v1/wish-list/remove-all`,
      SEND_TO_CART: `${API_URL}/api/v1/wish-list/send-to-cart`,
      SEND_ALL_TO_CART: `${API_URL}/api/v1/wish-list/send-all-to-cart`,
    },
    CART: {
      ONE: `${API_URL}/api/v1/cart`,
      ADD: `${API_URL}/api/v1/cart/add`,
      REMOVE: `${API_URL}/api/v1/cart/remove`,
      REMOVE_ALL: `${API_URL}/api/v1/cart/remove-all`,
      WISHLIST_ITEMS: `${API_URL}/api/v1/cart/wishlist-items`,
    },
  },
  CATEGORY: {
    ONE: `${API_URL}/api/v1/category`,
    PRODUCTS: `${API_URL}/api/v1/product/all`,
  },
  SUB_CATEGORY: {
    ONE: `${API_URL}/api/v1/sub-category`,
    PRODUCTS: `${API_URL}/api/v1/product/all`,
  },
  PRODUCT: {
    ONE: `${API_URL}/api/v1/product`,
    COMMENTS: `${API_URL}/api/v1/comment/all`,
    ADD_COMMENT: `${API_URL}/api/v1/comment/create`,
    EDIT_COMMENT: `${API_URL}/api/v1/comment/update`,
    DELETE_COMMENT: `${API_URL}/api/v1/comment/delete`,
    SUGGESTED: `${API_URL}/api/v1/product/suggested`,
  },
  SEARCH: {
    ROOT: `${API_URL}/api/v1/search`,
    PRODUCTS: `${API_URL}/api/v1/search/products`,
  },
  USER: {
    PROFILE: `${API_URL}/api/v1/user`,
    NATIONALITY_STATIC_LIST: `${API_URL}/api/v1/nationality/all-static`,
    UPDATE_PROFILE: `${API_URL}/api/v1/user/update`,
    CONTEXT: `${API_URL}/api/v1/user-context`,
  },
  VERIFY_EMAIL: {
    VERIFY: `${API_URL}/api/v1/authentication/verify-email`,
    REVERIFY: `${API_URL}/api/v1/authentication/resend-verification-email`,
  },
  CHECKOUT: {
    PROCESS_PAYMENT: `${API_URL}/api/v1/payment/process`,
    VERIFY_PAYMENT: `${API_URL}/api/v1/payment/verify`,
    SUBMIT_PAYMENT: `${API_URL}/api/v1/payment/checkout`,
    CHECKOUT_PAYMENT: `${API_URL}/api/v1/payment/checkout`,
  },
  ORDER: {
    Root: `${API_URL}/api/v1/order`,
    ChangePaymentStatus: `${API_URL}/api/v1/order/:id/change-payment-status`,
    ChangeDeliveryStatus: `${API_URL}/api/v1/order/:id/change-delivery-status`,
    Delete: `${API_URL}/api/v1/order/delete/:id`,
    UnDelete: `${API_URL}/api/v1/order/un-delete/:id`,
    GetAll: `${API_URL}/api/v1/order/all`,
    Create: `${API_URL}/api/v1/order/create`,
    GetOne: `${API_URL}/api/v1/order/:id`,
    GetMyOrders: `${API_URL}/api/v1/order/my-orders`,
    GetMyOrderReturns: `${API_URL}/api/v1/order/my-orders/$uid/returns`,
    GetMyOrder: `${API_URL}/api/v1/order/my-order`,
    Export: `${API_URL}/api/v1/order/export`,
  },
};
