export enum Statuses {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",

  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  PREPARING = "PREPARING",
  SHIPPED = "SHIPPED",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  RETURNED = "RETURNED",
  CANCELED = "CANCELED",

  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  PAID = "PAID",
  
  INTERNAL = "INTERNAL",
  OUTSOURCED = "OUTSOURCED",
}
