export const STATIC_NATIONALITIES = [
  // Arab Countries
  { code: 'JO', name: { en: 'Jordanian', ar: 'أردني' }, flag: '🇯🇴' },
  { code: 'SA', name: { en: 'Saudi', ar: 'سعودي' }, flag: '🇸🇦' },
  { code: 'EG', name: { en: 'Egyptian', ar: 'مصري' }, flag: '🇪🇬' },
  { code: 'AE', name: { en: 'Emirati', ar: 'إماراتي' }, flag: '🇦🇪' },
  { code: 'QA', name: { en: 'Qatari', ar: 'قطري' }, flag: '🇶🇦' },
  { code: 'KW', name: { en: 'Kuwaiti', ar: 'كويتي' }, flag: '🇰🇼' },
  { code: 'OM', name: { en: 'Omani', ar: 'عُماني' }, flag: '🇴🇲' },
  { code: 'BH', name: { en: 'Bahraini', ar: 'بحريني' }, flag: '🇧🇭' },
  { code: 'LB', name: { en: 'Lebanese', ar: 'لبناني' }, flag: '🇱🇧' },
  { code: 'SY', name: { en: 'Syrian', ar: 'سوري' }, flag: '🇸🇾' },
  { code: 'IQ', name: { en: 'Iraqi', ar: 'عراقي' }, flag: '🇮🇶' },
  { code: 'PS', name: { en: 'Palestinian', ar: 'فلسطيني' }, flag: '🇵🇸' },
  { code: 'YE', name: { en: 'Yemeni', ar: 'يمني' }, flag: '🇾🇪' },
  { code: 'MA', name: { en: 'Moroccan', ar: 'مغربي' }, flag: '🇲🇦' },
  { code: 'DZ', name: { en: 'Algerian', ar: 'جزائري' }, flag: '🇩🇿' },
  { code: 'TN', name: { en: 'Tunisian', ar: 'تونسي' }, flag: '🇹🇳' },
  { code: 'SD', name: { en: 'Sudanese', ar: 'سوداني' }, flag: '🇸🇩' },
  { code: 'LY', name: { en: 'Libyan', ar: 'ليبي' }, flag: '🇱🇾' },
  { code: 'KM', name: { en: 'Comoran', ar: 'قمري' }, flag: '🇰🇲' },
  { code: 'DJ', name: { en: 'Djiboutian', ar: 'جيبوتي' }, flag: '🇩🇯' },
  { code: 'MR', name: { en: 'Mauritanian', ar: 'موريتاني' }, flag: '🇲🇷' },
  { code: 'SO', name: { en: 'Somali', ar: 'صومالي' }, flag: '🇸🇴' },

  // Non-Arab Countries
  { code: 'PK', name: { en: 'Pakistani', ar: 'باكستاني' }, flag: '🇵🇰' },
  { code: 'IN', name: { en: 'Indian', ar: 'هندي' }, flag: '🇮🇳' },
  { code: 'PH', name: { en: 'Filipino', ar: 'فلبيني' }, flag: '🇵🇭' },
  { code: 'TR', name: { en: 'Turkish', ar: 'تركي' }, flag: '🇹🇷' },
  { code: 'US', name: { en: 'American', ar: 'أمريكي' }, flag: '🇺🇸' },
  { code: 'GB', name: { en: 'British', ar: 'بريطاني' }, flag: '🇬🇧' },
  { code: 'FR', name: { en: 'French', ar: 'فرنسي' }, flag: '🇫🇷' },
  { code: 'DE', name: { en: 'German', ar: 'ألماني' }, flag: '🇩🇪' },
  { code: 'IT', name: { en: 'Italian', ar: 'إيطالي' }, flag: '🇮🇹' },
  { code: 'ES', name: { en: 'Spanish', ar: 'إسباني' }, flag: '🇪🇸' },
  { code: 'CA', name: { en: 'Canadian', ar: 'كندي' }, flag: '🇨🇦' },
  { code: 'AU', name: { en: 'Australian', ar: 'أسترالي' }, flag: '🇦🇺' },
  { code: 'CN', name: { en: 'Chinese', ar: 'صيني' }, flag: '🇨🇳' },
  { code: 'RU', name: { en: 'Russian', ar: 'روسي' }, flag: '🇷🇺' },
  { code: 'BR', name: { en: 'Brazilian', ar: 'برازيلي' }, flag: '🇧🇷' },
  { code: 'MX', name: { en: 'Mexican', ar: 'مكسيكي' }, flag: '🇲🇽' },
  { code: 'JP', name: { en: 'Japanese', ar: 'ياباني' }, flag: '🇯🇵' },
  { code: 'KR', name: { en: 'South Korean', ar: 'كوري جنوبي' }, flag: '🇰🇷' },
  { code: 'NL', name: { en: 'Dutch', ar: 'هولندي' }, flag: '🇳🇱' },
  { code: 'SE', name: { en: 'Swedish', ar: 'سويدي' }, flag: '🇸🇪' },
  { code: 'NO', name: { en: 'Norwegian', ar: 'نرويجي' }, flag: '🇳🇴' },
  { code: 'DK', name: { en: 'Danish', ar: 'دنماركي' }, flag: '🇩🇰' },
  { code: 'FI', name: { en: 'Finnish', ar: 'فنلندي' }, flag: '🇫🇮' },
  { code: 'PT', name: { en: 'Portuguese', ar: 'برتغالي' }, flag: '🇵🇹' },
  { code: 'GR', name: { en: 'Greek', ar: 'يوناني' }, flag: '🇬🇷' },
  { code: 'IE', name: { en: 'Irish', ar: 'إيرلندي' }, flag: '🇮🇪' },
  { code: 'PL', name: { en: 'Polish', ar: 'بولندي' }, flag: '🇵🇱' },
  { code: 'AR', name: { en: 'Argentinian', ar: 'أرجنتيني' }, flag: '🇦🇷' },
  { code: 'CL', name: { en: 'Chilean', ar: 'تشيلي' }, flag: '🇨🇱' },
  { code: 'PE', name: { en: 'Peruvian', ar: 'بيروفي' }, flag: '🇵🇪' },
  { code: 'CO', name: { en: 'Colombian', ar: 'كولومبي' }, flag: '🇨🇴' },
  { code: 'VE', name: { en: 'Venezuelan', ar: 'فنزويلي' }, flag: '🇻🇪' },
  { code: 'NG', name: { en: 'Nigerian', ar: 'نيجيري' }, flag: '🇳🇬' },
  { code: 'ZA', name: { en: 'South African', ar: 'جنوب أفريقي' }, flag: '🇿🇦' },
  { code: 'KE', name: { en: 'Kenyan', ar: 'كيني' }, flag: '🇰🇪' },
  { code: 'GH', name: { en: 'Ghanaian', ar: 'غاني' }, flag: '🇬🇭' },
  { code: 'TH', name: { en: 'Thai', ar: 'تايلاندي' }, flag: '🇹🇭' },
  { code: 'VN', name: { en: 'Vietnamese', ar: 'فيتنامي' }, flag: '🇻🇳' },
  { code: 'ID', name: { en: 'Indonesian', ar: 'إندونيسي' }, flag: '🇮🇩' },
  { code: 'MY', name: { en: 'Malaysian', ar: 'ماليزي' }, flag: '🇲🇾' },
  { code: 'CH', name: { en: 'Swiss', ar: 'سويسري' }, flag: '🇨🇭' },
  { code: 'AT', name: { en: 'Austrian', ar: 'نمساوي' }, flag: '🇦🇹' },
];