export const PAGINATION_LIMITS = {
  INITIAL_TOTAL_USERS_LIMIT: 10,
  INITIAL_ACTIVE_USERS_LIMIT: 10,
  INITIAL_ADMIN_USERS_LIMIT: 10,
  INITIAL_DELETED_USERS_LIMIT: 10,
  TOTAL_USERS_LIMIT: 10,
  TOTAL_CATEGORIES_LIMIT: 10,
  TOTAL_SUB_CATEGORIES_LIMIT: 10,
  TOTAL_PRODUCTS_LIMIT: 10,
};
