export const PAGINATION_LIMITS = {
  TOTAL_USERS: 10,
  ACTIVE_USERS: 10,
  ADMIN_USERS: 10,
  DELETED_USERS: 10,
  CATEGORIES: 10,
  SUB_CATEGORIES: 10,
  PRODUCTS: 10,
  LOGOS: 10,
  BANNERS: 10,
  TYPE_HINT_CONFIGS: 10,
  SHOWCASES: 10,
  ACTIVE_ITEMS_IN_HOME_SHOWCASE: 5,
};
