export const validationConfig = {
  category: {
    nameMinChars: 3,
    nameMaxChars: 50,
    imageMinChars: 2,
  },
  subCategory: {
    nameMinChars: 3,
    nameMaxChars: 50,
    imageMinChars: 2,
  },
  logo: {
    nameMinChars: 3,
    nameMaxChars: 50,
    imageMinChars: 2,
    altTextMinChars: 3,
    altTextMaxChars: 50,
  },
  banner: {
    imageMinChars: 2,
    titleMinChars: 3,
    titleMaxChars: 50,
    bannerLinkMinChars: 5,
    bannerLinkMaxChars: 255,
  },
  typeHintConfig: {
    labelMinChars: 3,
    labelMaxChars: 50,
    iconMinChars: 3,
    iconMaxChars: 50,
    clrFromMinChars: 3,
    clrFromMaxChars: 50,
    clrToMinChars: 3,
    clrToMaxChars: 50,
    textClrMinChars: 3,
    textClrMaxChars: 50,
    priorityMinChars: 1,
    priorityMaxChars: 10,
  },
  showcase: {
    titleMinChars: 3,
    titleMaxChars: 50,
    descMinChars: 3,
    descMaxChars: 200,
    linkMinChars: 5,
    linkBtnTextMaxChars: 255,
    linkBtnTextMinChars: 5,
    linkMaxChars: 255,
  },
};
