export enum HandleAvailabilityReason {
  AVAILABLE = "AVAILABLE",
  INVALID = "INVALID",
  INVALID_FORMAT = "INVALID_FORMAT",
  CURRENT = "CURRENT",
  TAKEN = "TAKEN",
  RESERVED = "RESERVED",
  RECENTLY_RELEASED = "RECENTLY_RELEASED",
}
